### ISSUE TITLE
Error connecting to Postgres in Docker

### ISSUE THREAD

**Issue by alextanhongpin** [alextanhongpin/phoenix-starter#1]
```bash
=CRASH REPORT==== 3-Apr-2018::10:38:44 ===
  crasher:
    initial call: Elixir.DBConnection.Connection:init/1
    pid: <0.10711.0>
    registered_name: []
    exception exit: {#{'__exception__' => true,
                       '__struct__' => 'Elixir.RuntimeError',
                       message =>
                           <<"Connect raised a ArgumentError error. The exception details are hidden, as\nthey may contain sensitive data such as database credentials.\n">>},
                     [{'Elixir.Postgrex.Protocol',connect,1,
                          [{file,"lib/postgrex/protocol.ex"},{line,72}]},
                      {'Elixir.DBConnection.Connection',connect,2,
                          [{file,"lib/db_connection/connection.ex"},
                           {line,135}]},
                      {'Elixir.Connection',enter_connect,5,
                          [{file,"lib/connection.ex"},{line,622}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
      in function  'Elixir.Connection':enter_stop/5 (lib/connection.ex, line 686)
    ancestors: [<0.1313.0>,'Elixir.PhoenixStarter.Repo.Pool',
                  'Elixir.PhoenixStarter.Repo',
                  'Elixir.PhoenixStarter.Supervisor',<0.1309.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1313.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 3037
  neighbours:

=SUPERVISOR REPORT==== 3-Apr-2018::10:38:44 ===
     Supervisor: {<0.1313.0>,poolboy_sup}
     Context:    child_terminated
     Reason:     {#{'__exception__' => true,
                    '__struct__' => 'Elixir.RuntimeError',
                    message =>
                        <<"Connect raised a ArgumentError error. The exception details are hidden, as\nthey may contain sensitive data such as database credentials.\n">>},
                  [{'Elixir.Postgrex.Protocol',connect,1,
                       [{file,"lib/postgrex/protocol.ex"},{line,72}]},
                   {'Elixir.DBConnection.Connection',connect,2,
                       [{file,"lib/db_connection/connection.ex"},{line,135}]},
                   {'Elixir.Connection',enter_connect,5,
                       [{file,"lib/connection.ex"},{line,622}]},
                   {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.10711.0>},
                  {id,'Elixir.DBConnection.Poolboy.Worker'},
                  {mfargs,
                      {'Elixir.DBConnection.Poolboy.Worker',start_link,
                          undefined}},
                  {restart_type,temporary},
                  {shutdown,5000},
                  {child_type,worker}]

10:38:44.112 [error] GenServer #PID<0.10712.0> terminating
** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (postgrex) lib/postgrex/protocol.ex:72: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
```

**Comment by alextanhongpin** [comment]
```yml
version: '3.1'
services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_starter_prod
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  
  phoenix:
    # build: .
    image: alextanhongpin/phoenix
    environment:
      # - DB_USER=postgres
      # - DB_PASS=postgres
      # - DB_NAME=phoenix_starter_prod
      # - DB_HOST=db
      - PORT=4000
      # Add this to make it work
      - DATABASE_URL=postgres://postgres:postgres@db:5432/phoenix_starter_prod
    links:
      - db
    ports:
      - 127.0.0.1:4000:4000
```
